spring.application.name=auth-service
server.port=4005
jwt.secret=${JWT_SECRET:bXktcGF0aWVudC1tYW5hZ2VtZW50LXN5c3RlbS1qd3Qtc2VjcmV0LWtleS0yMDI2}

# === Datasource ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://auth-service-db:5432/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# === Hibernate ===
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# === SQL Init Mode ===
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
