version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_INIT_LIMIT: 5
    networks:
      - patient-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - patient-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - auth-service
      - patient-service
      - appointment-service
    networks:
      - patient-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    expose:
      - "4005"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - patient-network

  patient-service:
    build:
      context: ./patient-service
      dockerfile: Dockerfile
    expose:
      - "4000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - patient-network

  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    expose:
      - "4006"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - patient-network

networks:
  patient-network:
    driver: bridge


