server:
  port: 9000 # Gateway listens to this port

jwt:
  secret: ${JWT_SECRET:bXktcGF0aWVudC1tYW5hZ2VtZW50LXN5c3RlbS1qd3Qtc2VjcmV0LWtleS0yMDI2}

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis} #for rate limiting
      port: 6379
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            #uses token bucket algorithm, burstCapacity means, how many requests/secs are allowed
            #replishRate, once burstCapacity is reached, after 1 sec, bucket refills 5 tokens=5requests more
            redis-rate-limiter.burstCapacity: 5
            redis-rate-limiter.replenishRate: 5
            key-resolver: "#{@ipKeyResolver}"
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1 #Will remove auth from /auth/** to make http://auth-service:4005/**

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

        # Route for /api/patients/** to patient-service
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            # - JwtValidation #Can be used to have a middlerware filter before routing the request

        # Route for /api/docs/patients to patient-service /v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        # Route for /api/appointments/** to appointment-service
        - id: appointment-service-route
          uri: http://appointment-service:4006
          predicates:
            - Path=/api/appointments/**
          filters:
            - StripPrefix=1
            # - JwtValidation

        # Route for /api-docs/appointments to appointment-service /v3/api-docs
        - id: api-docs-appointment-route
          uri: http://appointment-service:4006
          predicates:
            - Path=/api-docs/appointments
          filters:
            - RewritePath=/api-docs/appointments,/v3/api-docs

        # Route for /api/doctors/** to doctor-service
        - id: doctor-service-route
          uri: http://doctor-service:4008
          predicates:
            - Path=/api/doctors/**
          filters:
            - StripPrefix=1

        # Route for /api-docs/doctors to doctor-service /v3/api-docs
        - id: api-docs-doctor-route
          uri: http://doctor-service:4008
          predicates:
            - Path=/api-docs/doctors
          filters:
            - RewritePath=/api-docs/doctors,/v3/api-docs
