spring.application.name=payment-service
server.port=4009

# === gRPC Server Configuration ===
grpc.server.port=9004

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://payment-service-db:5432/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

